
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Player")
public class Player {

    private String PlayerId;
    private String name;
    private String disk;

    public Player() {
        // Default constructor is required by AWS DynamoDB SDK
    }

    public Player(String name, String disk) {
        this.name = name;
        this.disk = disk;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return PlayerId;
    }

    public void setId(String id) {
        this.PlayerId = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getdisk() {
        return disk;
    }

    public void setdisk(String disk) {
        this.disk = disk;
    }
}